Add diagnostic info for automake and autoconf

diff --git a/src/Makevars b/src/Makevars
--- a/src/Makevars
+++ b/src/Makevars
@@ -73,6 +73,16 @@ libuv/m4/lt~obsolete.m4: libuv/m4/lt_obsolete.m4
 libuv/Makefile: libuv/m4/lt~obsolete.m4
 	cd libuv; \
 	if ! command -v automake >/dev/null 2>&1 ; then \
+		echo "automake NOT FOUND"; \
+	else \
+		echo "automake FOUND"; \
+	fi; \
+	if ! command -v autoconf >/dev/null 2>&1 ; then \
+		echo "autoconf NOT FOUND"; \
+	else \
+		echo "autoconf FOUND"; \
+	fi; \
+	if ! command -v automake >/dev/null 2>&1 ; then \
 		echo "automake not found. Touching files so configure will not try to run automake."; \
 		touch aclocal.m4; \
 		touch -r aclocal.m4 configure Makefile.in; \
